### ISSUE TITLE
Queue cutoff - should render a "cutoff bar", store ID of last ticket, move cutoff up and down

### ISSUE THREAD

**Issue by alexander-ding** [fullstackatbrown/hours-frontend#4]
https://github.com/nthnluu/hours-frontend/issues/29

**Comment by josue-creator** [comment]
- [x] modify the ticket struct models to include beforeCutoff
- [x] modify the backend routes to update new models
- [x] modify frontend to use these new routes
- [x] handle special cases like updating old tickets after reopening cutoff 
- [x] displays cutoff line on the frontend

**Comment by NicholasBottone** [comment]
~~Deprecated Development branches: [Frontend branch](https://github.com/fullstackatbrown/hours-frontend/tree/4-queue-cutoff) / [Backend branch](https://github.com/fullstackatbrown/hours-backend/tree/4-queue-cutoff)~~

Development branches: [Frontend branch](https://github.com/fullstackatbrown/hours-frontend/tree/4-queue-cutoff-new) / [Backend branch](https://github.com/fullstackatbrown/hours-backend/tree/4-queue-cutoff-new)

**Comment by NicholasBottone** [comment]
Josue and I finished renovating the cutoff system. Tickets now have a boolean `beforeCutoff` associated with them, and a cutoff line will render if the queue is cutoff, showing the `beforeCutoff=true` tickets above the line and the others below the line. When signups are reopened (when cutoff is turned off) all the tickets get changed to be `beforeCutoff=true`. If the queue is shuffled, the tickets before the cutoff line will be shuffled separately from those that are below the cutoff line. (We can change this behavior if necessary.)

We're not UI experts so there might still be some work to be done to improve how the cutoff line looks visually (we included some screenshots). Feel free to send feedback because there might still be a couple things left to finish up. We can create a PR if everything looks good to go.

![image](https://user-images.githubusercontent.com/13754214/160516731-7e40baf5-609b-427f-b572-aaecf02eca7e.png)
![image](https://user-images.githubusercontent.com/13754214/160516756-9c6740df-8555-44b0-bdba-c08abc07c8ee.png)

**Comment by NicholasBottone** [comment]
**Revised Plan**
- [x] modify the queue struct model to include a field representing the ticket ID of the last ticket before the cutoff (or null if the cutoff line is at the top / before any tickets)
- [x] modify the cutoff request to take in a ticket ID for the position the cutoff point should be
- [x] modify the backend endpoints to update new models
  - [x] starting cutoff mode should set the queue's cutoff ticket to be the id of the last ticket in the queue
  - [x] when a ticket is deleted, check if the ticket id matches the cutoff ticket - if this is the case, set the cutoff ticket to the ticket id of the ticket before this one (or null if this is the first ticket in the queue)
  - [x] when the queue is shuffled, disable the cutoff line
  - [x] when a ticket is marked as completed, do the same thing as when a ticket is deleted
- [x] modify the frontend to send the position the cutoff point should be with the cutoff request
- [x] display cutoff line on the frontend using the new information provided in the queue object
